services:
  server:
    build: .
    command: ["goback", "server"]
    working_dir: /app
    environment:
      - KEY_PATH=/app/private/id_rsa
  client:
    tty: true
    stdin_open: true
    build: .
    command: ["goback", "client"]
    depends_on:
      - server
    working_dir: /app
    environment:
      - KEY_PATH=/app/private/id_rsa
      - TERM=xterm-256color
    volumes:
      - ./test_files:/app/test_files
    deploy:
      replicas: 3 
