services:
  server:
    build: .
    command: ["goback", "server"]
    environment:
      - KEY_PATH=/app/private/id_rsa
    volumes:
      - ./data:/app/data
      - ./private/id_rsa:/app/private/id_rsa
  client:
    tty: true
    stdin_open: true
    build: .
    command: ["goback", "client"]
    depends_on:
      - server
    environment:
      - TERM=xterm-256color   
    volumes:
      - ./data:/app/data
    deploy:
      replicas: 3 
