services:
  server:
    build: .
    command: ["goback", "server"]
    ports:
      - "8080:8080"  # Replace with your server's port
    volumes:
      - ./data:/app/data
      - ./private/id_rsa:/app/private/id_rsa
  client:
    tty: true
    stdin_open: true
    build: .
    command: ["goback", "client"]
    depends_on:
      - server
    environment:
      - TERM=xterm-256color   # Add any environment variables needed for the client
    volumes:
      - ./data:/app/data
    deploy:
      replicas: 1 # Specifies the number of client replicas
